# Generated by Django 5.2.17 on 2026-09-02 21:48

import apps.design.models.entities
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('general_rules', models.TextField(blank=True, verbose_name='Reglas generales de uso')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palettes', to='projects.project')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_location', models.CharField(blank=True, max_length=180, verbose_name='Datos generales / ubicación')),
                ('business_notes', models.CharField(blank=True, max_length=255, verbose_name='Business / observación comercial')),
                ('social_notes', models.TextField(blank=True, verbose_name='Redes sociales / notas')),
                ('meeting_attendees', models.TextField(blank=True, verbose_name='Encargados / participantes')),
                ('logo_status', models.CharField(choices=[('has_logo', 'Ya tiene logo'), ('needs_logo', 'Necesita logo'), ('review', 'Debe modificarse / revisarse')], default='has_logo', max_length=20, verbose_name='Estado del logo')),
                ('logo_change_notes', models.TextField(blank=True, verbose_name='Cambios solicitados para el logo')),
                ('logo_format', models.CharField(choices=[('editable', 'Editable (AI, SVG, etc.)'), ('image', 'Imagen (PNG, JPG)'), ('unknown', 'No sabe')], default='unknown', max_length=20, verbose_name='Formato del logo')),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='design/logos/', verbose_name='Logo para vista/PDF (opcional)')),
                ('visual_structure', models.CharField(choices=[('simple', 'Sencilla'), ('visual', 'Visual'), ('high_design', 'Muy diseñada')], default='visual', max_length=24, verbose_name='Estructura visual de la web')),
                ('visual_structure_notes', models.TextField(blank=True, verbose_name='Detalle de estructura / animaciones')),
                ('style_direction', models.CharField(choices=[('minimal', 'Minimalista'), ('modern', 'Moderno'), ('corporate', 'Corporativo'), ('premium', 'Premium / elegante'), ('bold', 'Fuerte / llamativo'), ('friendly', 'Cercano / amigable'), ('custom', 'Personalizado')], default='modern', max_length=30, verbose_name='Dirección de estilo')),
                ('color_base_notes', models.TextField(blank=True, verbose_name='Base del diseño / colores solicitados')),
                ('background_style', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('mixed', 'Mixto (blanco + secciones con color)')], default='mixed', max_length=20, verbose_name='Estilo de color y fondo')),
                ('photo_availability', models.CharField(choices=[('own', 'Tiene fotos propias'), ('none', 'No tiene fotos'), ('partial', 'Tiene algunas fotos')], default='partial', max_length=20, verbose_name='Imágenes del cliente')),
                ('stock_usage', models.CharField(choices=[('mix', 'Mezcla (propias + profesionales)'), ('professional', 'Mayormente profesionales'), ('none', 'No usar stock')], default='mix', max_length=20, verbose_name='Uso de stock')),
                ('services', models.TextField(blank=True, verbose_name='Servicios principales')),
                ('page_style_notes', models.TextField(blank=True, verbose_name='Estilo esperado de la página')),
                ('typography_direction', models.TextField(blank=True, verbose_name='Tipografía / dirección de texto')),
                ('layout_preferences', models.TextField(blank=True, verbose_name='Distribución y composición')),
                ('visual_references', models.TextField(blank=True, verbose_name='Referencias visuales / URLs')),
                ('elements_to_avoid', models.TextField(blank=True, verbose_name='Elementos que no se deben usar')),
                ('designer_notes', models.TextField(blank=True, verbose_name='Notas internas de diseño')),
                ('completed', models.BooleanField(default=False, verbose_name='Asesoría visual completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_design_briefs', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_brief', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaletteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('text', 'Texto'), ('background', 'Fondo'), ('primary', 'Primario'), ('secondary', 'Secundario'), ('accent', 'Acento'), ('extra', 'Extra')], default='extra', max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('hex_code', models.CharField(max_length=7, validators=[apps.design.models.entities.validate_hex])),
                ('usage', models.CharField(blank=True, help_text='Ej.: botones, fondo, títulos.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='design.colorpalette')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaletteGradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Degradado', max_length=80)),
                ('start_hex', models.CharField(max_length=7, validators=[apps.design.models.entities.validate_hex])),
                ('end_hex', models.CharField(max_length=7, validators=[apps.design.models.entities.validate_hex])),
                ('order', models.PositiveIntegerField(default=0)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradients', to='design.colorpalette')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
