# Generated by Django 5.2.17 on 2026-09-03 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        ('plans', '0002_clientplan_assigned_design_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('client_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_social_months', to='plans.clientplan', verbose_name='Plan del cliente')),
            ],
            options={
                'ordering': ['-year', '-month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_posts', models.PositiveSmallIntegerField(default=0)),
                ('target_videos', models.PositiveSmallIntegerField(default=0)),
                ('posts_completed', models.BooleanField(default=False, verbose_name='Posts realizados')),
                ('videos_completed', models.BooleanField(default=False, verbose_name='Videos realizados')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('month_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='design.socialmediamonth')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_design_social_weeks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='socialmediamonth',
            constraint=models.UniqueConstraint(fields=('client_plan', 'year', 'month'), name='unique_design_social_month'),
        ),
        migrations.AddConstraint(
            model_name='socialmediaweek',
            constraint=models.UniqueConstraint(fields=('month_control', 'week_number'), name='unique_design_social_week'),
        ),
    ]
