# Generated by Django 5.2.17 on 2026-09-03 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_socialmediamonth_socialmediaweek_and_more'),
        ('plans', '0003_alter_serviceplan_options_clientplan_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaweek',
            name='month_control',
        ),
        migrations.RemoveField(
            model_name='socialmediaweek',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='SocialMediaCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='Inicio del ciclo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Próxima renovación')),
                ('client_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_cycles', to='plans.clientplan', verbose_name='Plan Social Media del cliente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_social_media_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('video', 'Video')], max_length=12)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('ready', models.BooleanField(default=False, verbose_name='Contenido listo')),
                ('published_networks', models.JSONField(blank=True, default=list, verbose_name='Publicado en')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notas')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_social_media_items', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='design.socialmediacycle')),
            ],
            options={
                'ordering': ['content_type', 'sequence', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='SocialMediaMonth',
        ),
        migrations.DeleteModel(
            name='SocialMediaWeek',
        ),
        migrations.AddConstraint(
            model_name='socialmediacycle',
            constraint=models.UniqueConstraint(fields=('client_plan', 'period_start'), name='unique_social_cycle_start'),
        ),
        migrations.AddConstraint(
            model_name='socialmediacontentitem',
            constraint=models.UniqueConstraint(fields=('cycle', 'content_type', 'sequence'), name='unique_social_content_item'),
        ),
    ]
