# Generated by Django 5.2.17 on 2026-09-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_designtaskcycleitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='designtaskcycleitem',
            new_name='design_desi_cycle_i_55342d_idx',
            old_name='design_desi_cycle_i_96ae28_idx',
        ),
    ]
