# Generated by Django 5.2.17 on 2026-09-02 21:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('project_type', models.CharField(choices=[('website', 'Página web'), ('software', 'Software'), ('social_media', 'Social Media'), ('seo', 'SEO'), ('branding', 'Branding'), ('other', 'Otro')], max_length=30)),
                ('status', models.CharField(choices=[('administration', 'Registro administrativo'), ('design_intake', 'Reunión de diseño'), ('development_intake', 'Levantamiento de desarrollo'), ('information_ready', 'Información lista'), ('in_development', 'En desarrollo'), ('review', 'Revisión'), ('delivered', 'Entregado'), ('paused', 'Pausado'), ('cancelled', 'Cancelado')], default='administration', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects_v2', to=settings.AUTH_USER_MODEL)),
                ('purchased_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='plans.clientplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('global', 'Global'), ('administration', 'Administración'), ('marketing', 'Marketing'), ('design', 'Diseño'), ('development', 'Desarrollo')], max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Asignado'), ('active', 'Activo'), ('done', 'Finalizado')], default='assigned', max_length=20)),
                ('responsibility', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects_v2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_notes_v2', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='projects_pr_project_573ce6_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'area'), name='unique_project_user_area_v2'),
        ),
    ]
