# Generated by Django 5.2.17 on 2026-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('administration', 'Registro administrativo (V2)'), ('design_intake', 'Diseño (V2)'), ('development_intake', 'Desarrollo (V2)'), ('information_ready', 'Información lista (V2)'), ('in_development', 'En desarrollo (V2)'), ('review', 'Revisión (V2)'), ('delivered', 'Entregado (V2)')], default='active', max_length=30),
        ),
    ]
