# Generated by Django 5.2.17 on 2026-09-03 20:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_serviceplan_branding_pages_serviceplan_scope_range_and_more'),
        ('projects', '0002_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('website', 'Página web'), ('software', 'Software'), ('social_media', 'Social Media'), ('seo', 'SEO'), ('branding', 'Branding'), ('other', 'Otro')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='purchased_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_projects', to='plans.clientplan'),
        ),
        migrations.CreateModel(
            name='ProjectPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio acordado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_plan_assignments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='plans.serviceplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracted_plans', to='projects.project')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_links', to='plans.clientplan', verbose_name='Suscripción vinculada')),
            ],
            options={
                'ordering': ['plan__department', 'plan__name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'plan'), name='unique_project_service_plan')],
            },
        ),
    ]
