# Generated by Django 5.2.17 on 2026-09-03 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0002_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Reunión con cliente', max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('meet_url', models.URLField(blank=True, help_text='Pega aquí el enlace de Google Meet. El módulo queda preparado para OAuth/Calendar futuro.')),
                ('external_attendees', models.TextField(blank=True, help_text='Correos externos, uno por línea.')),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('category', models.CharField(choices=[('six_weeks', 'Cumplimiento 6 semanas'), ('credential_renewal', 'Renovación de credenciales'), ('credential_purchase', 'Comprar credenciales'), ('followup_15', 'Seguimiento 15 días'), ('social_offer', 'Ofrecer Social Media'), ('social_monthly', 'Informe mensual Social Media'), ('social_daily', 'Seguimiento diario Social Media'), ('campaign_manager_review', 'Revisión Gerencia campaña'), ('campaign_weekly', 'Seguimiento semanal campaña'), ('meeting', 'Reunión'), ('google_reviews', 'Seguimiento reviews / Guarantee'), ('custom', 'Personalizado')], default='custom', max_length=40)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source_key', models.CharField(blank=True, db_index=True, help_text='Clave idempotente para recordatorios automáticos.', max_length=140)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.project')),
            ],
            options={
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='reminders_r_status_d19337_idx'), models.Index(fields=['category'], name='reminders_r_categor_f96d02_idx')],
            },
        ),
    ]
