# Generated by Django 5.2.17 on 2026-09-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_google_calendar_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='external_attendees',
            field=models.TextField(blank=True, help_text='Correos externos, uno por línea, coma o punto y coma.'),
        ),
    ]
