# Generated by Django 5.2.17 on 2026-09-03 13:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0002_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_name', models.CharField(max_length=180, verbose_name='Credencial / recurso')),
                ('provider', models.CharField(choices=[('godaddy', 'GoDaddy'), ('namecheap', 'Namecheap'), ('hostinger', 'Hostinger'), ('siteground', 'SiteGround'), ('google', 'Google'), ('meta', 'Meta'), ('youtube', 'YouTube'), ('other', 'Other')], default='google', max_length=30)),
                ('purchase_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('account_email', models.EmailField(blank=True, help_text='Correo/usuario de referencia. No se guardan contraseñas.', max_length=254)),
                ('secure_reference_url', models.URLField(blank=True, help_text='Link seguro/Drive donde el equipo autorizado administra el acceso.')),
                ('receipt_drive_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_purchases', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credential_purchases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_purchases', to='projects.project')),
            ],
            options={
                'ordering': ['renewal_date', '-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralManagementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='E')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('client_text', models.CharField(blank=True, max_length=180, verbose_name='Cliente libre')),
                ('detail_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre / Detalle')),
                ('service_type', models.CharField(choices=[('domain_host', 'Dominio y Host'), ('domain', 'Dominio'), ('host', 'Host'), ('monthly', 'Mensualidades'), ('credentials', 'Credenciales'), ('google_guarantee', 'Google Guarantee'), ('google_business', 'Google Business Profile'), ('ads', 'Ads'), ('other', 'Otros')], max_length=30, verbose_name='Tipo Servicio')),
                ('provider', models.CharField(choices=[('godaddy', 'GoDaddy'), ('namecheap', 'Namecheap'), ('hostinger', 'Hostinger'), ('siteground', 'SiteGround'), ('google', 'Google'), ('meta', 'Meta'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=30, verbose_name='Proveedor')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('ceo_paid', 'Pagado por CEO'), ('pending', 'Pendiente'), ('reimbursement', 'Pendiente reembolso'), ('paid_other', 'Pagado por tercero')], default='ceo_paid', max_length=30, verbose_name='Estado')),
                ('receipt_drive_url', models.URLField(blank=True, verbose_name='Link Recibo Drive')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_management_records', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_general_management_records', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_management_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='operations__date_0e9ff0_idx'), models.Index(fields=['service_type'], name='operations__service_67a649_idx'), models.Index(fields=['provider'], name='operations__provide_7869da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='REFERENCIA')),
                ('project_site', models.CharField(max_length=240, verbose_name='Proyecto/Sitio')),
                ('plan_start', models.DateField(blank=True, null=True, verbose_name='Inicio plan')),
                ('design_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto'), ('no_design', 'No diseño')], default='incomplete', max_length=20, verbose_name='DISEÑO')),
                ('tech_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='ESTADO TEC')),
                ('status', models.CharField(choices=[('finished', 'terminado'), ('delivered', 'entregado'), ('pending_payment', 'pendiente pago'), ('pending_web', 'pendiente web'), ('start', 'iniciar')], default='start', max_length=30, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo')),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Anticipo')),
                ('website_url', models.URLField(blank=True, verbose_name='Link web final')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='clients.client')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to=settings.AUTH_USER_MODEL, verbose_name='COLABORADOR')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='operations__status_f4e2e2_idx'), models.Index(fields=['plan_start'], name='operations__plan_st_e5cee2_idx')],
            },
        ),
    ]
