# Generated by Django 5.2.17 on 2026-09-03 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('projects', '0002_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProductionCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=180, verbose_name='Condado')),
                ('complexity', models.CharField(choices=[('S', 'S · Simple'), ('M', 'M · Media'), ('C', 'C · Compleja')], default='M', max_length=2)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.CharField(blank=True, max_length=220)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.TextField(blank=True, verbose_name='Palabras secundarias')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión')),
                ('seo_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO OK')),
                ('state', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_production_counties', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_web_production_counties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebProductionCountyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=180, verbose_name='Servicio')),
                ('complexity', models.CharField(choices=[('S', 'S · Simple'), ('M', 'M · Media'), ('C', 'C · Compleja')], default='M', max_length=2)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.CharField(blank=True, max_length=220)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.TextField(blank=True, verbose_name='Palabras secundarias')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión')),
                ('seo_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO OK')),
                ('state', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='operations.webproductioncounty')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_production_county_services', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_web_production_county_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebProductionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_page_target', models.PositiveIntegerField(default=8, verbose_name='Cantidad páginas principales')),
                ('county_target', models.PositiveIntegerField(default=0, verbose_name='Cantidad de condados')),
                ('services_per_county_target', models.PositiveIntegerField(default=0, verbose_name='Servicios por condado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas generales de producción')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_production_sheet', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_web_production_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='WebProductionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('principal', 'Principal'), ('extra', 'Extra')], default='principal', max_length=20)),
                ('name', models.CharField(blank=True, max_length=180, verbose_name='Página')),
                ('complexity', models.CharField(choices=[('S', 'S · Simple'), ('M', 'M · Media'), ('C', 'C · Compleja')], default='M', max_length=2)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.CharField(blank=True, max_length=220)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.TextField(blank=True, verbose_name='Palabras secundarias')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión')),
                ('seo_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO OK')),
                ('state', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_production_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_web_production_pages', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='operations.webproductionsheet')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='webproductioncounty',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='operations.webproductionsheet'),
        ),
    ]
