# Generated by Django 5.2.17 on 2026-09-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_webproductioncounty_webproductioncountyservice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webproductioncountyservice',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Servicio global'),
        ),
        migrations.AddField(
            model_name='webproductioncountyservice',
            name='service_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Servicio base'),
        ),
        migrations.AddField(
            model_name='webproductionsheet',
            name='header_structure',
            field=models.TextField(blank=True, default='Home | About | Services | Areas We Service | Gallery | Contact | Free Estimate', verbose_name='Estructura de header'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='complexity',
            field=models.CharField(choices=[('S', 'Simple'), ('M', 'Media'), ('C', 'Compleja')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='review_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión realizada'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='seo_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO legacy'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='state',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Página lista'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='complexity',
            field=models.CharField(choices=[('S', 'Simple'), ('M', 'Media'), ('C', 'Compleja')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='review_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión realizada'),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='seo_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO legacy'),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='state',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Página lista'),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='complexity',
            field=models.CharField(choices=[('S', 'Simple'), ('M', 'Media'), ('C', 'Compleja')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='review_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión realizada'),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='seo_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO legacy'),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='state',
            field=models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Página lista'),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WebProductionCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=180, verbose_name='Página')),
                ('complexity', models.CharField(choices=[('S', 'Simple'), ('M', 'Media'), ('C', 'Compleja')], default='S', max_length=2)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.CharField(blank=True, max_length=220)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('secondary_keywords', models.TextField(blank=True, verbose_name='Palabras secundarias')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Revisión realizada')),
                ('seo_status', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='SEO legacy')),
                ('state', models.CharField(choices=[('complete', 'Completo'), ('incomplete', 'Incompleto')], default='incomplete', max_length=20, verbose_name='Página lista')),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='operations.webproductioncounty')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='operations.webproductionsheet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ciudades de producción web',
                'ordering': ['order', 'id'],
            },
        ),
    ]
