# Generated by Django 5.2.17 on 2026-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_webproductioncountyservice_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webproductionsheet',
            name='cities_per_county_target',
            field=models.PositiveIntegerField(default=0, verbose_name='Ciudades por condado'),
        ),
        migrations.AlterField(
            model_name='generalmanagementrecord',
            name='service_type',
            field=models.CharField(choices=[('domain_host', 'Dominio y Host'), ('domain', 'Solo dominio'), ('host', 'Solo host')], max_length=30, verbose_name='Tipo Servicio'),
        ),
    ]
