# Generated by Django 5.2.17 on 2026-09-04 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_webproductionsheet_cities_per_county_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webproductioncity',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisor'),
        ),
        migrations.AddField(
            model_name='webproductioncity',
            name='workflow_status',
            field=models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_progress', 'En progreso'), ('in_review', 'En revisión'), ('complete', 'Completo')], default='not_started', max_length=20, verbose_name='Estado de producción'),
        ),
        migrations.AddField(
            model_name='webproductioncounty',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisor'),
        ),
        migrations.AddField(
            model_name='webproductioncounty',
            name='workflow_status',
            field=models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_progress', 'En progreso'), ('in_review', 'En revisión'), ('complete', 'Completo')], default='not_started', max_length=20, verbose_name='Estado de producción'),
        ),
        migrations.AddField(
            model_name='webproductioncountyservice',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisor'),
        ),
        migrations.AddField(
            model_name='webproductioncountyservice',
            name='workflow_status',
            field=models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_progress', 'En progreso'), ('in_review', 'En revisión'), ('complete', 'Completo')], default='not_started', max_length=20, verbose_name='Estado de producción'),
        ),
        migrations.AddField(
            model_name='webproductionpage',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisor'),
        ),
        migrations.AddField(
            model_name='webproductionpage',
            name='workflow_status',
            field=models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_progress', 'En progreso'), ('in_review', 'En revisión'), ('complete', 'Completo')], default='not_started', max_length=20, verbose_name='Estado de producción'),
        ),
        migrations.AlterField(
            model_name='webproductioncity',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, verbose_name='Keyword principal'),
        ),
        migrations.AlterField(
            model_name='webproductioncity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='webproductioncity',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=220),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, verbose_name='Keyword principal'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='webproductioncounty',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=220),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, verbose_name='Keyword principal'),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='webproductioncountyservice',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=220),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, verbose_name='Keyword principal'),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='webproductionpage',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=220),
        ),
        migrations.CreateModel(
            name='WebProductionInternalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='Sección')),
                ('complexity', models.CharField(choices=[('S', 'Simple'), ('M', 'Media'), ('C', 'Compleja')], default='S', max_length=2)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('workflow_status', models.CharField(choices=[('not_started', 'Sin iniciar'), ('in_progress', 'En progreso'), ('in_review', 'En revisión'), ('complete', 'Completo')], default='not_started', max_length=20, verbose_name='Estado')),
                ('created', models.BooleanField(default=False, verbose_name='Creada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.PositiveIntegerField(default=0)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_sections', to='operations.webproductionsheet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sección interna de producción',
                'verbose_name_plural': 'Secciones internas de producción',
                'ordering': ['order', 'id'],
            },
        ),
    ]
