# Generated by Django 5.2.17 on 2026-09-03 20:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('operations', '0004_webproductionsheet_cities_per_county_target_and_more'),
        ('projects', '0003_alter_project_project_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainHostingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('new', 'Nuevo dominio'), ('existing', 'Dominio existente'), ('migration', 'Migración')], default='new', max_length=20, verbose_name='Tipo')),
                ('domain_name', models.CharField(blank=True, max_length=255, verbose_name='Dominio')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('domain_expiry_date', models.DateField(blank=True, null=True, verbose_name='Caducidad del dominio')),
                ('domain_status', models.CharField(choices=[('pending', 'Dominio pendiente'), ('ready', 'Dominio comprado / registrado'), ('migrated', 'Dominio migrado')], default='pending', max_length=20, verbose_name='Estado del dominio')),
                ('server_provider', models.CharField(choices=[('siteground', 'SiteGround'), ('hostinger', 'Hostinger'), ('godaddy', 'GoDaddy'), ('bluehost', 'Bluehost'), ('other', 'Otro')], default='siteground', max_length=30, verbose_name='Proveedor servidor / hosting')),
                ('server_provider_other', models.CharField(blank=True, max_length=120, verbose_name='Otro proveedor')),
                ('server_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo servidor / hosting')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Moneda')),
                ('receipt_drive_url', models.URLField(blank=True, verbose_name='Link recibo Google Drive')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_hosting_records', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domain_hosting_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_hosting_records', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_domain_hosting_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['domain_status'], name='operations__domain__631783_idx'), models.Index(fields=['domain_expiry_date'], name='operations__domain__366963_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(choices=[('google', 'Google / Gmail'), ('webmail', 'Webmail / correo corporativo'), ('siteground', 'SiteGround'), ('wordpress', 'WordPress'), ('google_business', 'Google Business'), ('google_ads', 'Google Ads'), ('google_lsa', 'Google LSA / Guarantee'), ('search_console', 'Google Search Console'), ('analytics', 'Google Analytics'), ('meta', 'Meta / Facebook'), ('youtube', 'YouTube'), ('other', 'Otro')], max_length=30, verbose_name='Credencial')),
                ('custom_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre personalizado')),
                ('account_email', models.CharField(blank=True, max_length=255, verbose_name='Correo / usuario')),
                ('password_encrypted', models.TextField(blank=True, editable=False)),
                ('login_url', models.URLField(blank=True, verbose_name='URL de acceso')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('visible_to_team', models.BooleanField(default=False, verbose_name='Visible en resumen para las áreas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_credentials', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_credentials', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_credentials', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__business_name', 'project__name', 'credential_type', 'id'],
                'indexes': [models.Index(fields=['credential_type', 'enabled'], name='operations__credent_4b53d4_idx'), models.Index(fields=['visible_to_team'], name='operations__visible_c734bd_idx')],
            },
        ),
    ]
