# Generated by Django 5.2.17 on 2026-09-03 20:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_domainhostingrecord_projectcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainhostingrecord',
            name='domain_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo del dominio'),
        ),
        migrations.AddField(
            model_name='domainhostingrecord',
            name='domain_receipt_drive_url',
            field=models.URLField(blank=True, default='', verbose_name='Recibo del dominio · Google Drive'),
        ),
        migrations.AddField(
            model_name='domainhostingrecord',
            name='server_receipt_drive_url',
            field=models.URLField(blank=True, default='', verbose_name='Recibo del hosting · Google Drive'),
        ),
        migrations.AlterField(
            model_name='domainhostingrecord',
            name='domain_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad del dominio'),
        ),
        migrations.AlterField(
            model_name='domainhostingrecord',
            name='domain_status',
            field=models.CharField(choices=[('pending_purchase', 'Pendiente de compra'), ('purchased', 'Comprado y registrado'), ('pending_migration', 'Pendiente de migración'), ('migrated', 'Migrado'), ('pending', 'Pendiente (legado)'), ('ready', 'Comprado / registrado (legado)')], default='pending_purchase', max_length=24, verbose_name='Estado del dominio'),
        ),
        migrations.AlterField(
            model_name='domainhostingrecord',
            name='receipt_drive_url',
            field=models.URLField(blank=True, verbose_name='Recibo Drive (legado)'),
        ),
        migrations.AlterField(
            model_name='projectcredential',
            name='credential_type',
            field=models.CharField(choices=[('google', 'Google / Gmail'), ('server', 'Servidor'), ('wordpress', 'WordPress'), ('meta', 'Meta'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('other', 'Otro'), ('webmail', 'Webmail / correo corporativo (legado)'), ('siteground', 'SiteGround (legado)'), ('google_business', 'Google Business (legado)'), ('google_ads', 'Google Ads (legado)'), ('google_lsa', 'Google LSA / Guarantee (legado)'), ('search_console', 'Google Search Console (legado)'), ('analytics', 'Google Analytics (legado)')], max_length=30, verbose_name='Credencial'),
        ),
        migrations.AlterField(
            model_name='projectcredential',
            name='custom_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre personalizado / proveedor'),
        ),
    ]
