# Generated by Django 5.2.17 on 2026-09-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_webproductionhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webproductionhistory',
            new_name='operations__sheet_i_85eb63_idx',
            old_name='operations__sheet_i_6d58d9_idx',
        ),
    ]
