# Generated by Django 5.2.17 on 2026-09-03 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplan',
            name='assigned_design_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_social_media_client_plans', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Diseño / Social Media'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='weekly_posts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Posts por semana'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='weekly_videos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Videos por semana'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='service_type',
            field=models.CharField(choices=[('website', 'Página web'), ('social_media', 'Social Media'), ('marketing', 'Marketing'), ('software', 'Software'), ('seo', 'SEO'), ('branding', 'Branding'), ('other', 'Otro')], max_length=30),
        ),
    ]
