# Generated by Django 5.2.17 on 2026-09-03 19:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_clientplan_assigned_design_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplan',
            options={'ordering': ['department', 'service_type', 'name']},
        ),
        migrations.AddField(
            model_name='clientplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='clientplan',
            name='paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Pagado hasta'),
        ),
        migrations.AddField(
            model_name='clientplan',
            name='renewal_frequency',
            field=models.CharField(choices=[('none', 'Sin renovación'), ('weekly', 'Cada semana'), ('biweekly', 'Cada 15 días'), ('monthly', 'Cada mes'), ('every_monday', 'Todos los lunes')], default='monthly', max_length=24, verbose_name='Renovación'),
        ),
        migrations.AddField(
            model_name='clientplan',
            name='social_networks',
            field=models.JSONField(blank=True, default=list, verbose_name='Redes sociales'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='department',
            field=models.CharField(choices=[('administration', 'Administración'), ('design', 'Diseño'), ('marketing', 'Marketing'), ('developer', 'Desarrollo')], default='administration', max_length=24, verbose_name='Área responsable'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio acordado'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='assigned_design_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_social_media_client_plans', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Diseño'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='currency',
            field=models.CharField(default='USD', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin / vencimiento'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Parcial'), ('paid', 'Pagado')], default='pending', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Se renueva el'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='status',
            field=models.CharField(choices=[('quoted', 'Cotizado'), ('purchased', 'Comprado'), ('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='billing_cycle',
            field=models.CharField(choices=[('one_time', 'Pago único'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='one_time', max_length=20, verbose_name='Facturación'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='code',
            field=models.SlugField(max_length=80, unique=True, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='currency',
            field=models.CharField(default='USD', max_length=8, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notas del plan'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Nombre del plan'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='service_type',
            field=models.CharField(choices=[('website', 'Página web'), ('social_media', 'Social Media'), ('marketing', 'Marketing'), ('software', 'Software'), ('seo', 'SEO'), ('branding', 'Branding'), ('other', 'Otro')], max_length=30, verbose_name='Tipo / categoría'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='weekly_posts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de posts'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='weekly_videos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de videos'),
        ),
    ]
