# Generated by Django 5.2.17 on 2026-09-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_serviceplan_options_clientplan_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='branding_pages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de branding pages'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='scope_range',
            field=models.CharField(blank=True, max_length=120, verbose_name='Rango / alcance'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='website_pages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de páginas'),
        ),
        migrations.AlterField(
            model_name='clientplan',
            name='renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo pago / renovación'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='department',
            field=models.CharField(choices=[('administration', 'Administración'), ('design', 'Diseño'), ('marketing', 'Marketing'), ('developer', 'Sitios web / Desarrollo')], default='administration', max_length=24, verbose_name='Área responsable'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notas / alcance'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='service_type',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('jackets', 'Chaquetas'), ('caps', 'Gorras'), ('branding', 'Branding'), ('graphic_design', 'Diseño gráfico'), ('other_design', 'Otro de Diseño'), ('website', 'Sitio web'), ('landing_page', 'Landing page'), ('ecommerce', 'E-commerce'), ('website_maintenance', 'Mantenimiento web'), ('seo', 'SEO web'), ('software', 'Software'), ('other_web', 'Otro de Sitios web'), ('marketing', 'Plan de marketing'), ('google_guarantee', 'Google Guarantee'), ('google_search_console', 'Google Search Console'), ('google_ads', 'Google Ads'), ('google_lsa', 'Google LSA'), ('meta_ads', 'Meta Ads'), ('google_business', 'Google Business Profile'), ('other_marketing', 'Otro de Marketing'), ('domain_host', 'Dominio y Host'), ('credentials', 'Credenciales'), ('other_admin', 'Otro de Administración'), ('other', 'Otro')], max_length=40, verbose_name='Categoría'),
        ),
    ]
