# Generated by Django 5.2.17 on 2026-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_generalauditcheck'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generalauditcheck',
            new_name='audit_gener_area_80c755_idx',
            old_name='audit_gener_area_50bc70_idx',
        ),
        migrations.RenameIndex(
            model_name='generalauditcheck',
            new_name='audit_gener_project_159aaf_idx',
            old_name='audit_gener_project_d48d02_idx',
        ),
    ]
