# Generated by Django 5.2.17 on 2026-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_audit_decision_managementtask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='managementtask',
            new_name='audit_manag_area_cdfc5f_idx',
            old_name='audit_manag_area_st_733fb5_idx',
        ),
        migrations.RenameIndex(
            model_name='managementtask',
            new_name='audit_manag_assigne_a423ac_idx',
            old_name='audit_manag_assigne_3b1952_idx',
        ),
        migrations.RenameIndex(
            model_name='managementtask',
            new_name='audit_manag_project_119b81_idx',
            old_name='audit_manag_project_8f4087_idx',
        ),
        migrations.AlterField(
            model_name='generalauditcheck',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='generalauditcheck',
            name='note',
            field=models.TextField(blank=True, verbose_name='Observaciones de auditoría'),
        ),
    ]
