# Generated by Django 5.2.17 on 2026-09-03 16:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_name', models.CharField(blank=True, max_length=140, verbose_name='Rol / cargo')),
                ('period', models.CharField(help_text='Ej.: Septiembre 2026', max_length=80, verbose_name='Periodo')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sueldo / base')),
                ('extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Bonos / extras')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuentos')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=120, verbose_name='Forma de pago')),
                ('payroll_receipt_url', models.URLField(blank=True, verbose_name='Rol de pago / recibo Drive')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personnel_payments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_payments', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_personnel_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='finance_per_status_cf4196_idx'), models.Index(fields=['payment_date'], name='finance_per_payment_d8ee9d_idx')],
            },
        ),
    ]
