# Generated by Django 5.2.17 on 2026-09-03 21:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_personnelpayment'),
        ('plans', '0004_serviceplan_branding_pages_serviceplan_scope_range_and_more'),
        ('projects', '0003_alter_project_project_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='recurring_period',
            field=models.CharField(choices=[('none', 'No recurrente'), ('weekly', 'Semanal'), ('biweekly', 'Cada 15 días'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('provider', models.CharField(help_text='Ej.: Adobe, Envato, CapCut, Elementor', max_length=160, verbose_name='Proveedor')),
                ('detail', models.CharField(help_text='Ej.: Creative Cloud Pro', max_length=220, verbose_name='Nombre / detalle')),
                ('kind', models.CharField(choices=[('subscription', 'Mensualidad / suscripción'), ('tool', 'Herramienta / software'), ('plugin', 'Plugin / licencia'), ('service', 'Servicio operativo'), ('advertising', 'Publicidad / plataforma'), ('other', 'Otro')], default='subscription', max_length=24, verbose_name='Tipo')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('ceo_paid', 'Pagado por CEO'), ('pending', 'Pendiente'), ('reimbursement', 'Pendiente reembolso'), ('paid_other', 'Pagado por tercero')], default='ceo_paid', max_length=24, verbose_name='Estado')),
                ('recurring_period', models.CharField(choices=[('none', 'No recurrente'), ('weekly', 'Semanal'), ('biweekly', 'Cada 15 días'), ('monthly', 'Mensual'), ('yearly', 'Anual'), ('custom', 'Personalizado')], default='none', max_length=20, verbose_name='Renovación')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próximo pago')),
                ('receipt_drive_url', models.URLField(blank=True, verbose_name='Link recibo Drive')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operating_expenses', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_operating_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='finance_ope_date_ddea90_idx'), models.Index(fields=['status'], name='finance_ope_status_0b60e0_idx'), models.Index(fields=['next_due_date'], name='finance_ope_next_du_dbabd5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto recibido')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('payment_method', models.CharField(blank=True, max_length=120, verbose_name='Forma de pago')),
                ('receipt_drive_url', models.URLField(blank=True, verbose_name='Comprobante / recibo Drive')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_payments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='projects.project')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['payment_date'], name='finance_pro_payment_b0dd78_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(verbose_name='Fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto recibido')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Pagado hasta')),
                ('payment_method', models.CharField(blank=True, max_length=120, verbose_name='Forma de pago')),
                ('receipt_drive_url', models.URLField(blank=True, verbose_name='Comprobante / recibo Drive')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='plans.clientplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['payment_date'], name='finance_sub_payment_a288d3_idx'), models.Index(fields=['paid_until'], name='finance_sub_paid_un_1e5dc4_idx')],
            },
        ),
    ]
