# Generated by Django 5.2.17 on 2026-09-03 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status'),
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitemap_url', models.URLField(blank=True)),
                ('last_sitemap_read', models.DateField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_projects_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_status', to='projects.project')),
            ],
            options={
                'verbose_name': 'Estado SEO del proyecto',
                'verbose_name_plural': 'Estados SEO de proyectos',
                'ordering': ['project__client__business_name'],
            },
        ),
        migrations.CreateModel(
            name='SEOUrlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('page_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('objective', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('indexed', 'Indexada'), ('not_indexed', 'No indexada'), ('pending', 'Pendiente'), ('unknown', 'Sin revisar')], default='unknown', max_length=20)),
                ('current_position', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('previous_position', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('last_sitemap_read', models.DateField(blank=True, null=True)),
                ('pending_action', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('alert', models.CharField(choices=[('ok', 'Sin alerta'), ('monitor', 'Monitorear'), ('attention', 'Atención'), ('critical', 'Crítica')], default='monitor', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_urls_created', to=settings.AUTH_USER_MODEL)),
                ('seo_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='questionnaires.seoprojectstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_urls_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL SEO',
                'verbose_name_plural': 'URLs SEO',
                'ordering': ['order', 'id'],
            },
        ),
    ]
