# Generated by Django 5.2.17 on 2026-09-02 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_type', models.CharField(choices=[('company', 'Empresa'), ('person', 'Persona')], default='company', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('identity_document', models.CharField(blank=True, max_length=80, verbose_name='ID / identificación')),
                ('business_name', models.CharField(max_length=180, verbose_name='Nombre de la empresa')),
                ('contact_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Número de teléfono')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=140, verbose_name='Categoría / industria')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state_region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('lead', 'Prospecto'), ('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['business_name'], name='clients_cli_busines_0fae8c_idx'), models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx')],
            },
        ),
    ]
