# Generated by Django 5.2.17 on 2026-09-03 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('marketing', '0001_initial'),
        ('projects', '0002_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('meta', 'Meta Ads'), ('google', 'Google Ads'), ('traditional', 'Pauta tradicional')], max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('account_id', models.CharField(blank=True, max_length=120)),
                ('objective', models.CharField(blank=True, max_length=180)),
                ('campaign_type', models.CharField(blank=True, max_length=180)),
                ('keyword_research', models.TextField(blank=True, help_text='Keywords o link al estudio.')),
                ('creative_notes', models.TextField(blank=True, help_text='Ideas/propuesta y brief para Diseño.')),
                ('manager_review_notes', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('manager_review', 'Revisión Gerencia'), ('ready', 'Lista para lanzar'), ('launched', 'Lanzada'), ('completed', 'Finalizada'), ('paused', 'Pausada')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_summary', models.TextField(blank=True, verbose_name='Datos recolectados de la reunión')),
                ('owner_name', models.CharField(blank=True, max_length=180, verbose_name='Nombre del dueño')),
                ('legal_business_name', models.CharField(blank=True, max_length=220, verbose_name='Nombre legal de la empresa')),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fundación')),
                ('social_links', models.TextField(blank=True, verbose_name='Redes sociales')),
                ('company_description', models.TextField(blank=True, verbose_name='Descripción de la empresa')),
                ('business_hours', models.TextField(blank=True, verbose_name='Horario')),
                ('services', models.TextField(blank=True, verbose_name='Servicios')),
                ('service_areas', models.TextField(blank=True, verbose_name='Áreas')),
                ('gmail_email', models.EmailField(blank=True, max_length=254, verbose_name='Gmail creado')),
                ('business_profile_status', models.CharField(choices=[('not_started', 'No iniciado'), ('verification', 'En verificación'), ('approved', 'Aprobado'), ('denied', 'Desaprobado')], default='not_started', max_length=30, verbose_name='Verificación Google Business')),
                ('business_profile_link', models.URLField(blank=True, verbose_name='Link Google Business')),
                ('review_link', models.URLField(blank=True, verbose_name='Link para reviews')),
                ('review_message', models.TextField(blank=True, verbose_name='Mensaje para customers')),
                ('documents_available', models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=10, verbose_name='¿Tiene documentos?')),
                ('credentials_group_requested', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='Credenciales pedidas por grupo')),
                ('pdf_documents_requested', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='Documentos PDF solicitados')),
                ('google_ads_verification', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('google_lsa_verification', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('google_guarantee_launched', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_workspaces', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_workspace', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='marketing_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('drive_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_marketing_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marketing.marketingworkspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('next_report_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_plans', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_plans', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_plans', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviews', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('products', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('profile_percentage', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='Porcentaje perfil')),
                ('google_business', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='GB')),
                ('networks', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='REDES')),
                ('website_in_gb', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='WEBSITE EN GB')),
                ('last_post_gb', models.DateField(blank=True, null=True, verbose_name='Último Post GB')),
                ('gb_notes', models.TextField(blank=True, verbose_name='Notas GB')),
                ('lsa', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('photos', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='FOTOS')),
                ('last_lead', models.CharField(blank=True, max_length=80, verbose_name='Último Lead')),
                ('ads_verified', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20, verbose_name='ADS VERIFICADO')),
                ('google_followup', models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], default='no', max_length=10, verbose_name='Seguimiento con Google?')),
                ('notes', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_tracking', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_tracking_rows', to='projects.project')),
            ],
            options={
                'ordering': ['client__business_name'],
            },
        ),
        migrations.CreateModel(
            name='MarketingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('intake', 'Recolección / reunión'), ('google_profile', 'Google Business Profile'), ('google_lsa', 'Google LSA / Guarantee'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('social_media', 'Social Media')], max_length=30)),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('yes_no', models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='marketing.marketingworkspace')),
            ],
            options={
                'ordering': ['area', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'key'), name='unique_marketing_workspace_check_key')],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('follow_up', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('publication', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo')], default='incomplete', max_length=20)),
                ('post_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='marketing.socialmediaplan')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'date'), name='unique_social_daily_plan_date')],
            },
        ),
    ]
