# Generated by Django 5.2.17 on 2026-09-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_adcampaign_marketingworkspace_marketingdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingworkspace',
            name='business_profile_mode',
            field=models.CharField(blank=True, choices=[('existing', 'Ya tiene perfil'), ('create', 'Crear perfil'), ('no', 'No tiene / no crear')], default='', max_length=20, verbose_name='Google Business: situación'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='shared_info_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última edición compartida'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='shared_info_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shared_marketing_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Última edición compartida por'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='webmail_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Webmail / correo corporativo'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='webmail_has',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='', max_length=10, verbose_name='¿Cuenta con webmail?'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='webmail_secure_reference_url',
            field=models.URLField(blank=True, help_text='Usa un link seguro/Drive; no guardes contraseñas en texto plano.', verbose_name='Referencia segura de credenciales'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='website_has',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], default='', max_length=10, verbose_name='¿Tiene sitio web?'),
        ),
        migrations.AddField(
            model_name='marketingworkspace',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Sitio web actual'),
        ),
    ]
