# Generated by Django 5.2.17 on 2026-09-02 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(help_text='Ej.: Roofing, Siding, Gutters', max_length=140)),
                ('image_url', models.URLField(max_length=1000, verbose_name='URL de foto / carpeta')),
                ('source', models.CharField(blank=True, help_text='Drive, Shutterstock, cliente, etc.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_references', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_references', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('administration', 'Administración'), ('design', 'Diseño'), ('development', 'Desarrollo'), ('marketing', 'Marketing'), ('global', 'Global')], default='design', max_length=24)),
                ('kind', models.CharField(choices=[('palette_drive', 'Drive - paleta'), ('summary_backup', 'Drive - resumen / respaldo'), ('logo', 'Logo / identidad'), ('photos', 'Banco de fotos'), ('document', 'Documento'), ('other', 'Otro')], default='other', max_length=24)),
                ('label', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_resource_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='projects.project')),
            ],
            options={
                'ordering': ['area', 'kind', 'label'],
            },
        ),
    ]
