# Generated by Django 5.2.17 on 2026-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresourcelink',
            name='kind',
            field=models.CharField(choices=[('information', 'Información / resumen'), ('palette_drive', 'Drive - paleta'), ('summary_backup', 'Drive - resumen / respaldo'), ('logo', 'Logo / identidad'), ('photos', 'Banco de fotos'), ('document', 'Documento'), ('other', 'Otro')], default='other', max_length=24),
        ),
    ]
