# Generated by Django 5.2.17 on 2026-09-02 21:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('registrar', models.CharField(blank=True, max_length=120)),
                ('provider_url', models.URLField(blank=True)),
                ('account_email', models.EmailField(blank=True, help_text='Correo de la cuenta. No se almacenan contraseñas en texto plano.', max_length=254)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('annual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('auto_renew', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('planned', 'Por registrar'), ('active', 'Activo'), ('renewal_due', 'Por renovar'), ('expired', 'Vencido'), ('transferred', 'Transferido'), ('cancelled', 'Cancelado')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domains', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='projects.project')),
            ],
            options={
                'ordering': ['domain_name'],
                'indexes': [models.Index(fields=['status'], name='domains_dom_status_e71c1c_idx'), models.Index(fields=['renewal_date'], name='domains_dom_renewal_a28a7b_idx')],
            },
        ),
    ]
