# Generated by Django 5.2.17 on 2026-09-18 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state_region', models.CharField(blank=True, max_length=100, verbose_name='Estado / Provincia')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('company', models.CharField(blank=True, max_length=180, verbose_name='Empresa')),
                ('interested_service', models.CharField(blank=True, max_length=180, verbose_name='Servicio interesado')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Fuente')),
                ('campaign', models.CharField(blank=True, max_length=180, verbose_name='Campaña')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('pending', 'Pendiente de contacto'), ('contacted', 'Contactado'), ('follow_up', 'Seguimiento'), ('meeting_proposed', 'Meet propuesto'), ('meeting_done', 'Meet realizado'), ('potential', 'Cliente potencial'), ('won', 'Venta cerrada'), ('no_response', 'No responde'), ('unqualified', 'No calificado'), ('lost', 'Perdido')], db_index=True, default='new', max_length=30, verbose_name='Estado')),
                ('quality', models.CharField(choices=[('undefined', 'Sin definir'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='undefined', max_length=20, verbose_name='Calidad')),
                ('loss_reason', models.CharField(blank=True, choices=[('no_response', 'No respondió'), ('fake_number', 'Número falso'), ('duplicate', 'Duplicado'), ('not_interested', 'No interesado'), ('price', 'Precio'), ('no_budget', 'Sin presupuesto'), ('service_unavailable', 'Servicio no disponible'), ('out_of_area', 'Fuera de zona'), ('other_company', 'Contrató otra empresa'), ('researching', 'Solo averiguaba'), ('spam', 'Spam'), ('other', 'Otro')], max_length=40, verbose_name='Motivo de pérdida')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Último contacto')),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Próximo seguimiento')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to=settings.AUTH_USER_MODEL, verbose_name='Vendedora asignada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='Fecha y hora')),
                ('contact_type', models.CharField(choices=[('phone', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'Meet'), ('other', 'Otro')], default='phone', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='sales.lead')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('answered', 'Contestó'), ('no_answer', 'No contestó'), ('whatsapp', 'Respondió por WhatsApp'), ('email', 'Respondió por email'), ('wrong_number', 'Número incorrecto'), ('not_interested', 'No interesado'), ('out_of_budget', 'Fuera de presupuesto'), ('contact_later', 'Solicita contacto después'), ('accepts_meeting', 'Acepta meet')], max_length=30)),
                ('channel', models.CharField(choices=[('phone', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('other', 'Otro')], default='phone', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_contact_attempts', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='sales.lead')),
            ],
            options={
                'ordering': ['-contacted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='sales.lead')),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_assignments_to', to=settings.AUTH_USER_MODEL)),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_assignments_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('meeting_type', models.CharField(blank=True, max_length=80, verbose_name='Tipo de reunión')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('completed', 'Realizado'), ('no_show', 'No asistió'), ('cancelled', 'Cancelado'), ('rescheduled', 'Reprogramado')], db_index=True, default='scheduled', max_length=20)),
                ('result', models.TextField(blank=True, verbose_name='Resultado')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_meetings', to='sales.lead')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='sales_lead_status_b6ddbf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_at', 'assigned_to'], name='sales_lead_next_fo_52ab47_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'due_at', 'assigned_to'], name='sales_follo_status_871baa_idx'),
        ),
    ]
